postinst: cleanup cloud-id-shim on xenial->bionic

diff --git a/debian/ubuntu-advantage-tools.postinst b/debian/ubuntu-advantage-tools.postinst
--- a/debian/ubuntu-advantage-tools.postinst
+++ b/debian/ubuntu-advantage-tools.postinst
@@ -37,6 +37,7 @@ OLD_MESSAGING_TIMER="ua-messaging.timer"
 OLD_MESSAGING_TIMER_MASKED_LOCATION="/etc/systemd/system/timers.target.wants/$OLD_MESSAGING_TIMER"
 OLD_LICENSE_CHECK_PATH="ua-license-check.path"
 OLD_LICENSE_CHECK_PATH_MASKED_LOCATION="/etc/systemd/system/multi-user.target.wants/$OLD_LICENSE_CHECK_PATH"
+XENIAL_CLOUD_ID_SHIM_UNIT_LOCATION="/etc/systemd/system/multi-user.target.wants/ubuntu-advantage-cloud-id-shim.service"
 
 ESM_APT_PREF_FILE_TRUSTY="$APT_PREFERENCES_DIR/ubuntu-esm-trusty"
 ESM_INFRA_OLD_APT_PREF_FILE_TRUSTY="$APT_PREFERENCES_DIR/ubuntu-esm-infra-trusty"
@@ -329,7 +330,8 @@ disable_new_timer_if_old_timer_already_disabled() {
     fi
 }
 
-remove_old_systemd_timers() {
+remove_old_systemd_units() {
+    PREVIOUS_PKG_VER=$1
     # These are the commands that are run when the package is purged.
     # Since we actually want to remove this service from now on
     # we have replicated that behavior here
@@ -352,6 +354,17 @@ remove_old_systemd_timers() {
         fi
         deb-systemd-helper purge ua-license-check.path > /dev/null || true
         deb-systemd-helper unmask ua-license-check.path > /dev/null || true
+    fi
+
+    # If we're do-release-upgrad-ing to bionic, then clean up the xenial-only
+    # cloud-id-shim unit
+    if [ "$VERSION_ID" = "18.04" ]; then
+        if echo "$PREVIOUS_PKG_VER" | grep -q "16.04"; then
+            if [ -L $XENIAL_CLOUD_ID_SHIM_UNIT_LOCATION ]; then
+                deb-systemd-helper purge ubuntu-advantage-cloud-id-shim.service > /dev/null || true
+                deb-systemd-helper unmask ubuntu-advantage-cloud-id-shim.service > /dev/null || true
+            fi
+        fi
     fi
 }
 
@@ -424,7 +437,7 @@ case "$1" in
       mark_reboot_for_fips_pro
       rm_old_license_check_marker
       disable_new_timer_if_old_timer_already_disabled $PREVIOUS_PKG_VER
-      remove_old_systemd_timers
+      remove_old_systemd_units $PREVIOUS_PKG_VER
       /usr/lib/ubuntu-advantage/cloud-id-shim.sh || true
       ;;
 esac
