license-check: remove timer-based license-check

diff --git a/debian/ubuntu-advantage-tools.postinst b/debian/ubuntu-advantage-tools.postinst
--- a/debian/ubuntu-advantage-tools.postinst
+++ b/debian/ubuntu-advantage-tools.postinst
@@ -35,6 +35,8 @@ OLD_CLIENT_FIPS_PPA="private-ppa.launchpad.net/ubuntu-advantage/fips/ubuntu"
 UA_TIMER_NAME="ua-timer.timer"
 OLD_MESSAGING_TIMER="ua-messaging.timer"
 OLD_MESSAGING_TIMER_MASKED_LOCATION="/etc/systemd/system/timers.target.wants/$OLD_MESSAGING_TIMER"
+OLD_LICENSE_CHECK_PATH="ua-license-check.path"
+OLD_LICENSE_CHECK_PATH_MASKED_LOCATION="/etc/systemd/system/multi-user.target.wants/$OLD_LICENSE_CHECK_PATH"
 
 ESM_APT_PREF_FILE_TRUSTY="$APT_PREFERENCES_DIR/ubuntu-esm-trusty"
 ESM_INFRA_OLD_APT_PREF_FILE_TRUSTY="$APT_PREFERENCES_DIR/ubuntu-esm-infra-trusty"
@@ -49,7 +51,7 @@ SYSTEMD_HELPER_ENABLED_AUTO_ATTACH_DSH="/var/lib/systemd/deb-systemd-helper-enab
 SYSTEMD_HELPER_ENABLED_WANTS_LINK="/var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/ua-auto-attach.service"
 
 REBOOT_CMD_MARKER_FILE="/var/lib/ubuntu-advantage/marker-reboot-cmds-required"
-LICENSE_CHECK_MARKER_FILE="/var/lib/ubuntu-advantage/marker-license-check"
+OLD_LICENSE_CHECK_MARKER_FILE="/var/lib/ubuntu-advantage/marker-license-check"
 
 MACHINE_TOKEN_FILE="/var/lib/ubuntu-advantage/private/machine-token.json"
 
@@ -309,15 +311,8 @@ notify_wrong_fips_metapackage_on_cloud() {
     fi
 }
 
-enable_periodic_license_check() {
-    cloud_id=$(cloud-id 2>/dev/null) || cloud_id=""
-    if echo "$cloud_id" | grep -q "^gce"; then
-        if check_is_lts "${UBUNTU_CODENAME}"; then
-            if [ ! -f $MACHINE_TOKEN_FILE ]; then
-                touch $LICENSE_CHECK_MARKER_FILE
-            fi
-        fi
-    fi
+rm_old_license_check_marker() {
+    rm -f $OLD_LICENSE_CHECK_MARKER_FILE
 }
 
 disable_new_timer_if_old_timer_already_disabled() {
@@ -360,6 +355,22 @@ remove_old_systemd_timers() {
             deb-systemd-helper purge ua-messaging.timer > /dev/null || true
             deb-systemd-helper unmask ua-messaging.timer > /dev/null || true
         fi
+    fi
+    if [ -L $OLD_LICENSE_CHECK_PATH_MASKED_LOCATION ]; then
+        if [ -d /run/systemd/system ]; then
+            # If the old ua-license-check.timer was running during upgrade
+            # then it will be in a failed state because the files were removed
+            # The failed state is ephemeral and only needs to be cleared if
+            # it is there so that the system doesn't say it is degraded.
+            # If the old timer was not running, then this is a noop.
+            systemctl --system daemon-reload > /dev/null || true
+            systemctl reset-failed ua-license-check.timer > /dev/null 2>&1 || true
+            # In rare race-condition scenarios, the service can also get into
+            # the same failed state.
+            systemctl reset-failed ua-license-check.service > /dev/null 2>&1 || true
+        fi
+        deb-systemd-helper purge ua-license-check.path > /dev/null || true
+        deb-systemd-helper unmask ua-license-check.path > /dev/null || true
     fi
 }
 
@@ -439,7 +450,7 @@ case "$1" in
         fi
       fi
       mark_reboot_for_fips_pro
-      enable_periodic_license_check
+      rm_old_license_check_marker
       disable_new_timer_if_old_timer_already_disabled $PREVIOUS_PKG_VER
       remove_old_systemd_timers
       ;;
